-- USER SQL
CREATE USER "C##DBETAPA1" IDENTIFIED BY "123"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS

-- ROLES
GRANT "DBA" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "DV_MONITOR" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "CTXAPP" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "DV_AUDIT_CLEANUP" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "EM_EXPRESS_ALL" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "WM_ADMIN_ROLE" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "OLAP_USER" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "OLAP_XS_ADMIN" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "DV_SECANALYST" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "RECOVERY_CATALOG_OWNER_VPD" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "XS_CACHE_ADMIN" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "GDS_CATALOG_SELECT" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "SCHEDULER_ADMIN" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "PROVISIONER" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "AUDIT_ADMIN" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES_OVER_HTTP" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "DV_REALM_RESOURCE" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "AQ_ADMINISTRATOR_ROLE" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "SYSUMF_ROLE" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "APPLICATION_TRACE_VIEWER" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "DV_PUBLIC" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "LBAC_DBA" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "OPTIMIZER_PROCESSING_RATE" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "RECOVERY_CATALOG_USER" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "DV_DATAPUMP_NETWORK_LINK" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "GSMUSER_ROLE" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "GATHER_SYSTEM_STATISTICS" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "LOGSTDBY_ADMINISTRATOR" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "DBJAVASCRIPT" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "GSM_POOLADMIN_ROLE" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "DV_ADMIN" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "DV_POLICY_OWNER" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "HS_ADMIN_ROLE" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "XS_SESSION_ADMIN" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "DV_GOLDENGATE_ADMIN" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "IMP_FULL_DATABASE" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "DV_XSTREAM_ADMIN" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "DV_PATCH_ADMIN" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "GGSYS_ROLE" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "EJBCLIENT" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "HS_ADMIN_EXECUTE_ROLE" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "JMXSERVER" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "OLAP_DBA" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "ADM_PARALLEL_EXECUTE_TASK" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "JAVAIDPRIV" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "SELECT_CATALOG_ROLE" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "JAVADEBUGPRIV" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "CONNECT" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "SODA_APP" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "OEM_MONITOR" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "GSMADMIN_ROLE" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "AQ_USER_ROLE" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "JAVAUSERPRIV" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "XDB_SET_INVOKER" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "RECOVERY_CATALOG_OWNER" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "JAVA_ADMIN" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "DBFS_ROLE" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "PDB_DBA" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "RDFCTX_ADMIN" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "DV_GOLDENGATE_REDO_ACCESS" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "CDB_DBA" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "JAVASYSPRIV" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "HS_ADMIN_SELECT_ROLE" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "AUDIT_VIEWER" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "RESOURCE" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "DV_OWNER" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "XDB_WEBSERVICES_WITH_PUBLIC" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "EXECUTE_CATALOG_ROLE" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "DATAPATCH_ROLE" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "DV_ACCTMGR" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "DV_REALM_OWNER" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "EXP_FULL_DATABASE" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "DBMS_MDX_INTERNAL" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "DV_STREAMS_ADMIN" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "XS_NAMESPACE_ADMIN" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "ORDADMIN" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "AUTHENTICATEDUSER" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "CAPTURE_ADMIN" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "OEM_ADVISOR" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "XS_CONNECT" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "XDBADMIN" TO "C##DBETAPA1" WITH ADMIN OPTION;
GRANT "EM_EXPRESS_BASIC" TO "C##DBETAPA1" WITH ADMIN OPTION;

-- SYSTEM PRIVILEGES